# Generated by Django 4.2.1 on 2023-05-07 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_transaction_created_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 7, 13, 47, 18, 270722),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 7, 14, 2, 18, 270722), editable=False
            ),
        ),
    ]
