# Generated by Django 4.2.1 on 2023-05-07 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_transaction_created_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_id",
            new_name="txid",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 7, 23, 30, 15, 859412),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 7, 23, 45, 15, 859412),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.FloatField(default=0),
        ),
    ]
