# Generated by Django 4.2.1 on 2023-06-02 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_transaction_id_transaction_txid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                choices=[(1, "recive"), (2, "send")], default=2, max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 2, 11, 18, 41, 272938),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 2, 11, 33, 41, 272938),
                editable=False,
            ),
        ),
    ]
