# Generated by Django 4.2.1 on 2023-06-02 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_transaction_action_alter_transaction_created_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="state",
            field=models.CharField(
                choices=[(1, "recive"), (2, "send")], default=1, max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 2, 11, 52, 41, 681825),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 2, 12, 7, 41, 681825), editable=False
            ),
        ),
    ]
