# Generated by Django 4.2.1 on 2023-06-02 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_transaction_state_alter_transaction_created_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntrestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField()),
                (
                    "created_time",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 2, 12, 36, 12, 378984),
                        editable=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 2, 12, 36, 12, 378984),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 2, 12, 51, 12, 378984),
                editable=False,
            ),
        ),
    ]
