# Generated by Django 4.2.1 on 2023-06-15 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_intrestrate_alter_transaction_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intrestrate",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 15, 18, 40, 3, 689919),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 15, 18, 40, 3, 689919),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 15, 18, 55, 3, 689919),
                editable=False,
            ),
        ),
        migrations.CreateModel(
            name="ProfileAssesment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="uploads/")),
                (
                    "created_time",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 6, 15, 18, 40, 3, 690914),
                        editable=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
