# Generated by Django 4.2.1 on 2023-06-15 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_intrestrate_created_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="verified",
            field=models.CharField(
                choices=[(1, "No Request"), (2, "Pending"), (3, "Verified")],
                default=1,
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="intrestrate",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 15, 20, 4, 22, 21168), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="profileassesment",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 15, 20, 4, 22, 21168), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 15, 20, 4, 22, 21168), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expire_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 15, 20, 19, 22, 21168),
                editable=False,
            ),
        ),
    ]
